In [2]:
import numpy as np

In [123]:
eps = np.array((-.75, .25, .25, .25))
eps = np.array((-3, 1, 1, 1))
eps

array([-3,  1,  1,  1])

In [125]:
np.random.permutation(eps)

array([ 1,  1, -3,  1])

In [10]:
rng = np.random.default_rng()

In [119]:
signs = np.sign(np.random.random((3, 3))-.5)

In [179]:
Y, X = signs.shape
new_signs = (eps[:, None, None]*signs[None])#.transpose(1, 2, 0).reshape(Y*X, 4)
new_signs = rng.permuted(new_signs, axis=0)
new_signs = np.concatenate((np.concatenate(new_signs[:2], axis=0), np.concatenate(new_signs[2:], axis=0)), axis=1)

#new_signs = new_signs.reshape(Y, X, 4).transpose(2, 0, 1)
#new_signs = new_signs.reshape(2, 2, Y, X).transpose(0, 2, 1, 3).reshape(2*Y, 2*X)
#print(new_signs[-4:, -4:])

(6, 6)


In [177]:
signs

array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [ 1.,  1., -1.]])

In [178]:
t

array([[ 3., -1., -1., -1., -1.,  3.],
       [ 1., -1.,  3.,  1., -1., -1.],
       [ 1., -3., -1., -3.,  1.,  3.],
       [-1.,  3., -1., -1., -1., -1.],
       [-3.,  3., -1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1.,  1., -1.]])

In [128]:
new_signs

array([[[-1., -1., -1.],
        [ 1., -1., -1.],
        [ 1.,  1., -1.]],

       [[ 3.,  3.,  3.],
        [-3.,  3.,  3.],
        [-3., -3.,  3.]],

       [[-1., -1., -1.],
        [ 1., -1., -1.],
        [ 1.,  1., -1.]],

       [[-1., -1., -1.],
        [ 1., -1., -1.],
        [ 1.,  1., -1.]]])

In [107]:
np.concatenate(new_signs[:2], axis=0)[:

array([[ 0.25,  0.25],
       [-0.25, -0.25],
       [ 0.25,  0.25],
       [-0.25,  0.25]])

In [113]:
new_signs[3]

array([[ 0.25,  0.25,  0.25, ..., -0.25,  0.25,  0.25],
       [-0.25, -0.25,  0.25, ...,  0.25, -0.25, -0.25],
       [ 0.25,  0.25, -0.25, ..., -0.25,  0.25,  0.25],
       ...,
       [-0.25,  0.25, -0.25, ...,  0.25, -0.25, -0.25],
       [ 0.25,  0.25, -0.25, ...,  0.25,  0.25, -0.25],
       [-0.25,  0.25, -0.25, ..., -0.25,  0.25, -0.25]])